# Numpy test
This is a sample of numpy library functions - WEKTORY I MACIERZE

# Wektory 

In [3]:
import numpy as np

arr = np.array([1, 2, "1"])
dtype = arr.dtype

print(dtype)

<U21


In [4]:
import numpy as np

classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)


list

In [5]:
import numpy as np

classic_list = [1, 2, 3, 5, 7, 11]
type(classic_list)

# Ta lista może nam posłużyć jako parametr dla zbioru NumPy.

numpy_array = np.array(classic_list)
type(numpy_array)

numpy.ndarray

<div style="background-color: orange; padding: 20px;text-align: center;font-weight: bold;">
SZEREG ( w ARRAY), który powstał ma typ numpy.ndarray i jest to najważniejszy typ, jaki musisz zapamiętać z tego fragmentu o NumPy. Taki obiekt ma wymiary dostępne jako właściwość shape.
</div>

In [7]:
import numpy as np

classic_list = [1, 2, 3, 5, 7, 11]
numpy_array = np.array(classic_list)

numpy_array.shape

(6,)

Jak widzisz, wynik to (6,). Drugi wymiar nie jest uwzględniony, ponieważ wektor jest jednowymiarowy.

<div style="background-color: lightblue; padding:30px; text-align: center;font-weight: bold;">
    obliczenia na wektorach
</div>

Tworząc sobie wektor, możesz wywołać metody obliczające statyczne wielkości, takie jak średnia (mean) czy odchylenie standardowe (std)

In [11]:
np.array([2,4]).mean()


3.0

In [12]:
np.array([1,2,4,5,6,18,1,91]).std()

28.809720581775867

In [13]:
# dodawanie wektorów 
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

# Macierze

Zbiór jednakowo długich wektorów to macierz.

<div style="background-color: lightblue; padding:30px; text-align: center;font-weight: bold;">
    rozmiar macierzy
</div>

In [17]:
numpy_matrix = np.array([[1,2,3], [5,7,11]])
numpy_matrix.shape


(2, 3)

<div style="background-color: lightblue; padding:30px; text-align: center;font-weight: bold;">
    indeksacja macierzy i POBIERANIE  wiersza , kolumny, elementu z macierzy 
</div>

In [19]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])
# komenda pobrania wektora pierwszego 
matrix1[0, :]


array([1, 2, 3])

In [20]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])
# pobieranie kolumny ostatniej
matrix1[:, -1]

array([3, 6, 9])

In [21]:
matrix1 = np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])
# pobieranie elementu na przecięciu wiersza 1 i kolumny ostatniej
matrix1[0, -1]

3

<div style="background-color: lightblue; padding:30px; text-align: center;font-weight: bold;">
    operacje na macierzach 
</div>

W NumPy możesz szybko i bezpiecznie wykonywać dodawanie wektorów i macierzy. Takie operacje, jako 
<div style="background-color: white; padding:10px; text-align: center;font-weight: bold;">
podwaliny uczenia maszynowego, 
</div>
muszą być wykonywane szybko. 

In [24]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])
#suma wszystkich elementów 
matrix2.sum()

47

Chcielibyśmy jednak wejść nieco głębiej i zadać pytanie – jakie sumy mają całe wiersze i kolumny? Wtedy należy dodać parametr axis do danej metody statystycznej, np. sum. 

In [26]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])
#suma w kolumnach 
matrix2.sum(axis=0)

array([ 2, 20, 25])

In [27]:
matrix2 = np.array([
	[1,2,3],
	[0,8,10],
	[1,10,12]
])
#suma w wierszach 
matrix2.sum(axis=1)

array([ 6, 18, 23])

In [28]:
# dodawanie wektorów 
np.array([1,2]) + np.array([8,9])

array([ 9, 11])

In [29]:
# dodawanie macierzy 
np.array([
	[1,2],
	[3,4]
]) + \
np.array([
	[8,9],
	[10,11]
])


array([[ 9, 11],
       [13, 15]])

In [30]:
#mnożenie macierzy 

np.array([
	[1,2],
	[3,4]
]).dot([1,1])


array([3, 7])

#interpretacje powyższego: 

np.array([...]): Ten fragment kodu tworzy dwuwymiarową tablicę (macierz) za pomocą funkcji np.array z biblioteki NumPy. Wewnętrzne listy reprezentują wiersze macierzy.

#1 Macierz wejściowa:

[
 [1, 2],
 [3, 4]
]


#2 .dot([1, 1]): Następnie wywoływana jest metoda dot, która służy do mnożenia macierzy. Jednak w tym przypadku, drugi argument to jednowymiarowa tablica [1, 1], a nie druga macierz.

Teraz, dokonuje się mnożenia macierzy przez jednowymiarową tablicę. Mnożenie macierzy przez wektor to operacja, w której każdy wiersz macierzy jest mnożony przez kolejny element wektora, a wyniki są sumowane.

#3 Wynik mnożenia będzie wyglądać następująco:


[(1 * 1 + 2 * 1), (3 * 1 + 4 * 1)]
Po obliczeniach wynik będzie wyglądał tak:
[3, 7]
Ostateczny wynik to jednowymiarowa tablica [3, 7], która jest efektem mnożenia macierzy [1, 2], [3, 4] przez wektor [1, 1].

In [32]:
# inny przykład mnożenia 
np.array([
	[1,2],
	[3,4]
]).dot([2,1])

array([ 4, 10])

Wynik mnożenia będzie wyglądać następująco:


[(1 * 2 + 2 * 1), (3 * 2 + 4 * 1)]

# test 

dodawanie wektorów: Jeden z nich niech ma długość 10 i zawiera liczby od 1 do 10. Drugi będzie wektorem, który zawiera 10 jedynek. Jeśli chodzi o drugiego, nie jest twórzony ręcznie.

In [36]:
x = np.array([1,2,3,4,5,6,8,7,8,9,10]) 
y = np.ones(11).astype(int)
print(y)

[1 1 1 1 1 1 1 1 1 1 1]


In [37]:
x = np.array([1,2,3,4,5,6,8,7,8,9,10]) 
print(x)

[ 1  2  3  4  5  6  8  7  8  9 10]


In [38]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 8, 7, 8, 9, 10])
y = np.ones(11).astype(int)

res = x + y

print(res)

[ 2  3  4  5  6  7  9  8  9 10 11]


średnie wartości dla każdego wiersza i każdej kolumny.

macierz, która składa się z 5 wierszy i 5 kolumn. Wypełniona liczbami od 1 do 25 (czyli pierwszy wiersz będzie zawierał liczby od 1 do 5, następny od 6...).

In [40]:
import numpy as np

# Tworzenie macierzy
matrix = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])

# Obliczanie średnich dla każdego wiersza
average_row = np.mean(matrix, axis=1)

# Obliczanie średnich dla każdej kolumny
average_column = np.mean(matrix, axis=0)

print("Średnie dla każdego wiersza:")
print(average_row)

print("Średnie dla każdej kolumny:")
print(average_column)

Średnie dla każdego wiersza:
[ 3.  8. 13. 18. 23.]
Średnie dla każdej kolumny:
[11. 12. 13. 14. 15.]
